--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/vNozell/Minasui
build-by-default: true
branches:
 - main
projects:
 - MinasUi
categories:
  - tools
  - plugins
  - menu
  - mina
  -Minas
tags:
  - mina
  - ui
  - menu
  - tools
  - server
  - pocketmine
 screenshots:
  - https://cdn.discordapp.com/attachments/1120423792389390356/1149440176238633060/Screenshot_20230907-152047_Minecraft.jpg
 icon: https://cdn.discordapp.com/attachments/1120423792389390356/1149441992581972089/icon_para_un_plugin.jpg
...
